appVersion: apps/v1
kind: Deployment
metadata:
  name: shop
  namespace: shop
spec:
     replicas: 1
     selector: 
       matchLabels:
         labels:
            app: shop
     template:
       metadata:
         labels:
          app: shop
       spec:
         containers:
         - name: shop
           image: zuiweng518/shop:v2.0
---
apiVersion: v1
kind: Service
metadata:
  name: shop
  namespace: shop
 spec:
  selector:
    app: shop
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      name: master
      nodePort: 32000
